


spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
server:
  port: 9000


---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-event
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstrap.servers: 127.0.0.1:9092


---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9090
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer